version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - apps

  appservice:
    build: ./app
    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/blog_app?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - 8081:9091
    networks:
      - apps

networks:
  apps:
